package co.nz.pizzashack.client.integration.ws.client.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2014-02-01T10:49:18.394+13:00
 * Generated source version: 2.7.7
 * 
 */
@WebService(targetNamespace = "http://ws.integration.pizzashack.nz.co/", name = "BillingProcessWebServices")
@XmlSeeAlso({ObjectFactory.class})
public interface BillingProcessWebServices {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "billingProcess", targetNamespace = "http://ws.integration.pizzashack.nz.co/", className = "co.nz.pizzashack.client.integration.ws.client.stub.BillingProcess")
    @WebMethod
    @ResponseWrapper(localName = "billingProcessResponse", targetNamespace = "http://ws.integration.pizzashack.nz.co/", className = "co.nz.pizzashack.client.integration.ws.client.stub.BillingProcessResponse")
    public co.nz.pizzashack.client.integration.ws.client.stub.BillingResponse billingProcess(
        @WebParam(name = "arg0", targetNamespace = "")
        co.nz.pizzashack.client.integration.ws.client.stub.BillingDto arg0
    ) throws FaultMessage;
}
