
package co.nz.pizzashack.client.integration.ws.client.stub;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2014-02-01T10:49:18.350+13:00
 * Generated source version: 2.7.7
 * 
 */
public final class BillingProcessWebServices_BillingProcessWebServicesPort_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.integration.pizzashack.nz.co/", "BillingProcessWebServicesService");

    private BillingProcessWebServices_BillingProcessWebServicesPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = BillingProcessWebServicesService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        BillingProcessWebServicesService ss = new BillingProcessWebServicesService(wsdlURL, SERVICE_NAME);
        BillingProcessWebServices port = ss.getBillingProcessWebServicesPort();  
        
        {
        System.out.println("Invoking billingProcess...");
        co.nz.pizzashack.client.integration.ws.client.stub.BillingDto _billingProcess_arg0 = null;
        try {
            co.nz.pizzashack.client.integration.ws.client.stub.BillingResponse _billingProcess__return = port.billingProcess(_billingProcess_arg0);
            System.out.println("billingProcess.result=" + _billingProcess__return);

        } catch (FaultMessage e) { 
            System.out.println("Expected exception: FaultMessage has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
