package co.nz.pizzashack.client.integration.ws.client.stub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2014-02-01T10:49:18.399+13:00
 * Generated source version: 2.7.7
 * 
 */
@WebServiceClient(name = "BillingProcessWebServicesService", 
                  wsdlLocation = "http://localhost:8111/ws/billingWs?wsdl",
                  targetNamespace = "http://ws.integration.pizzashack.nz.co/") 
public class BillingProcessWebServicesService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.integration.pizzashack.nz.co/", "BillingProcessWebServicesService");
    public final static QName BillingProcessWebServicesPort = new QName("http://ws.integration.pizzashack.nz.co/", "BillingProcessWebServicesPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8111/ws/billingWs?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BillingProcessWebServicesService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8111/ws/billingWs?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BillingProcessWebServicesService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BillingProcessWebServicesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BillingProcessWebServicesService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BillingProcessWebServicesService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BillingProcessWebServicesService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BillingProcessWebServicesService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns BillingProcessWebServices
     */
    @WebEndpoint(name = "BillingProcessWebServicesPort")
    public BillingProcessWebServices getBillingProcessWebServicesPort() {
        return super.getPort(BillingProcessWebServicesPort, BillingProcessWebServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BillingProcessWebServices
     */
    @WebEndpoint(name = "BillingProcessWebServicesPort")
    public BillingProcessWebServices getBillingProcessWebServicesPort(WebServiceFeature... features) {
        return super.getPort(BillingProcessWebServicesPort, BillingProcessWebServices.class, features);
    }

}
