package co.nz.pizzashack.integration.ws.client.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2014-01-25T21:20:25.013+13:00
 * Generated source version: 2.7.7
 * 
 */
@WebService(targetNamespace = "http://ws.integration.billing.pizzashack.nz.co/", name = "BillingWebServices")
@XmlSeeAlso({ObjectFactory.class})
public interface BillingWebServices {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "accountAuthentication", targetNamespace = "http://ws.integration.billing.pizzashack.nz.co/", className = "co.nz.pizzashack.integration.ws.client.stub.AccountAuthentication")
    @WebMethod
    @ResponseWrapper(localName = "accountAuthenticationResponse", targetNamespace = "http://ws.integration.billing.pizzashack.nz.co/", className = "co.nz.pizzashack.integration.ws.client.stub.AccountAuthenticationResponse")
    public co.nz.pizzashack.integration.ws.client.stub.AccountTransactionRespDto accountAuthentication(
        @WebParam(name = "arg0", targetNamespace = "")
        co.nz.pizzashack.integration.ws.client.stub.AccountDto arg0
    ) throws FaultMessage;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllTransactionsForAccount", targetNamespace = "http://ws.integration.billing.pizzashack.nz.co/", className = "co.nz.pizzashack.integration.ws.client.stub.GetAllTransactionsForAccount")
    @WebMethod
    @ResponseWrapper(localName = "getAllTransactionsForAccountResponse", targetNamespace = "http://ws.integration.billing.pizzashack.nz.co/", className = "co.nz.pizzashack.integration.ws.client.stub.GetAllTransactionsForAccountResponse")
    public java.util.List<co.nz.pizzashack.integration.ws.client.stub.BillingTransactionDto> getAllTransactionsForAccount(
        @WebParam(name = "arg0", targetNamespace = "")
        co.nz.pizzashack.integration.ws.client.stub.AccountDto arg0
    ) throws FaultMessage;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "billingProcess", targetNamespace = "http://ws.integration.billing.pizzashack.nz.co/", className = "co.nz.pizzashack.integration.ws.client.stub.BillingProcess")
    @WebMethod
    @ResponseWrapper(localName = "billingProcessResponse", targetNamespace = "http://ws.integration.billing.pizzashack.nz.co/", className = "co.nz.pizzashack.integration.ws.client.stub.BillingProcessResponse")
    public co.nz.pizzashack.integration.ws.client.stub.AccountTransactionRespDto billingProcess(
        @WebParam(name = "arg0", targetNamespace = "")
        co.nz.pizzashack.integration.ws.client.stub.BillingTransactionDto arg0
    ) throws FaultMessage;
}
