package co.nz.pizzashack.integration.ws.client.stub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2014-01-25T21:20:25.021+13:00
 * Generated source version: 2.7.7
 * 
 */
@WebServiceClient(name = "BillingWebServicesService", 
                  wsdlLocation = "http://localhost:8112/pizzashackbilling/ws/accountWs?wsdl",
                  targetNamespace = "http://ws.integration.billing.pizzashack.nz.co/") 
public class BillingWebServicesService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.integration.billing.pizzashack.nz.co/", "BillingWebServicesService");
    public final static QName BillingWebServicesPort = new QName("http://ws.integration.billing.pizzashack.nz.co/", "BillingWebServicesPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8112/pizzashackbilling/ws/accountWs?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BillingWebServicesService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8112/pizzashackbilling/ws/accountWs?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BillingWebServicesService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BillingWebServicesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BillingWebServicesService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BillingWebServicesService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BillingWebServicesService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BillingWebServicesService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns BillingWebServices
     */
    @WebEndpoint(name = "BillingWebServicesPort")
    public BillingWebServices getBillingWebServicesPort() {
        return super.getPort(BillingWebServicesPort, BillingWebServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BillingWebServices
     */
    @WebEndpoint(name = "BillingWebServicesPort")
    public BillingWebServices getBillingWebServicesPort(WebServiceFeature... features) {
        return super.getPort(BillingWebServicesPort, BillingWebServices.class, features);
    }

}
