
package co.nz.pizzashack.client.integration.ws.client.pizzashack.stub;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.7
 * 2014-03-10T15:15:06.010+13:00
 * Generated source version: 2.7.7
 */

@WebFault(name = "fault", targetNamespace = "http://ws.integration.pizzashack.nz.co/")
public class FaultMessage extends Exception {
    
    private co.nz.pizzashack.client.integration.ws.client.pizzashack.stub.Fault fault;

    public FaultMessage() {
        super();
    }
    
    public FaultMessage(String message) {
        super(message);
    }
    
    public FaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public FaultMessage(String message, co.nz.pizzashack.client.integration.ws.client.pizzashack.stub.Fault fault) {
        super(message);
        this.fault = fault;
    }

    public FaultMessage(String message, co.nz.pizzashack.client.integration.ws.client.pizzashack.stub.Fault fault, Throwable cause) {
        super(message, cause);
        this.fault = fault;
    }

    public co.nz.pizzashack.client.integration.ws.client.pizzashack.stub.Fault getFaultInfo() {
        return this.fault;
    }
}
