package co.nz.pizzashack.client.integration.ws.client.pizzashack.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2014-03-10T15:15:06.018+13:00
 * Generated source version: 2.7.7
 * 
 */
@WebService(targetNamespace = "http://ws.integration.pizzashack.nz.co/", name = "PizzashackWs")
@XmlSeeAlso({ObjectFactory.class})
public interface PizzashackWs {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPizzashackByName", targetNamespace = "http://ws.integration.pizzashack.nz.co/", className = "co.nz.pizzashack.client.integration.ws.client.pizzashack.stub.GetPizzashackByName")
    @WebMethod
    @ResponseWrapper(localName = "getPizzashackByNameResponse", targetNamespace = "http://ws.integration.pizzashack.nz.co/", className = "co.nz.pizzashack.client.integration.ws.client.pizzashack.stub.GetPizzashackByNameResponse")
    public co.nz.pizzashack.client.integration.ws.client.pizzashack.stub.PizzashackDto getPizzashackByName(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws FaultMessage;
}
